# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24edff831446b78f10bc2a3d7874097174f88c00e6412f5b59d2d158b64632e3816f94660bbff628e3d97df1e1132e21ab75c8fc87b265a9ba5620edf9826d7e

test:
  secret_key_base: 15b6ded4828bcee363b3dd9c28931152127b085c42bfd2e212102558e4a4837757689c53bf420d544bec1c7ddd83fdcc005924fa0997de49b8a2c89dfd3f7eb7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
